### ISSUE TITLE
Jupyter kernel cannot be interrupted

### ISSUE THREAD

**Issue by molenik** [jupyter-vim/jupyter-vim#19]
#### Description
When sending code from `jupyter-vim` to a jupyter kernel, the kernel execution cannot be manually interrupted (e.g. by pressing Ctrl-C in the qtconsole). The only way to interrupt kernel is to restart it.

#### Reproduce bug
To replicate run the infinite loop below and try interrupting the kernel with `Ctrl-C` in the qtconsole
```python
import time
while True: 
    print('----------------')
    time.sleep(0.5)
```

#### Versions
I have the following setup
- nvim: 0.5.0
- jupyter core: 4.5.0
- qtconsole: 4.3.1
- jupyter client: 5.2.4

####

**Comment by wmvanvliet** [comment]
ah, good catch! Maybe this should be fixed on the QtConsole end. Having `jupyter-vim` have an interrupt kernel command is certainly possible, not would not be my first choice for an elegant solution. It's more intuitive for QtConsole to interrupt the kernel.

**Comment by molenik** [comment]
The way the same bug occurs with `jupyter console`. I've submitted an issue to QtConsole:  jupyter/qtconsole#410

**Comment by wmvanvliet** [comment]
Great, thanks! We'll follow it up there.

**Comment by ilkerhk** [comment]
I understand that this is a jupyter bug and it should be solved in jupyter side.
However, in qtconsole it is possible to interrupt a running code if it is not coming from a remote connection. So, it is possible that this bug might not be a high priority for jupyter team.

On the other hand, in jupyter-vim, the only way to interrupt a running code is to kill the kernel. I think, this makes jupyter-vim unusable for many users such as me. 
Otherwise, this is a very nice plugin.
