### ISSUE TITLE
After setting up everything according to the readme the qtconsole appears on a different console. How can I make it so it appears in another window in vim?

### ISSUE THREAD

**Issue by edlgg** [jupyter-vim/jupyter-vim#35]
Im not sure if this is the right place to ask this...

![Screenshot from 2020-09-08 11-46-20](https://user-images.githubusercontent.com/24853391/92504932-f4bcf980-f1c8-11ea-971b-9282fad066f1.png)

**Comment by tinmarino** [comment]
You are adviced to use tmux and an other shell. Because vim windows are not the best place for Read Eval Print Loop

Otherwise, start a terminal in a modern vim with `terminal` command and in thei terminal you can run `jupyter-console`. Once this jupyter-console in vim's terminal is opened, you can run `JupyterConnect` (or `JConnect` on dev branch).

**Comment by edlgg** [comment]
Thanks!
